parameters:
  - name: pool
    displayName: 'Agent Pool'
    type: string
    default: 'Self-hosted'
    values:
    - 'Azure Pipelines'
    - 'Self-hosted'

trigger:
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
      - master
      - main

resources:
  repositories:
    - repository: templates
      endpoint: thenoobsbr
      type: github
      name: TheNoobsBr/Azure-Templates
      ref: refs/heads/main

variables:
  - template: variables.yml

stages:
  - template: templates/gitflow_calculate_version.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
  - template: templates/library_build.yml@templates
    parameters:
      pool: ${{ parameters.pool }}
  - template: templates/library_deploy.yml@templates
    parameters:
      pool: ${{ parameters.pool }}