trigger:
  tags:
    include:
      - '*'

pr:
  branches:
    include:
      - develop
      - master
      - main

resources:
  repositories:
    - repository: templates
      endpoint: thenoobsbr
      type: github
      name: TheNoobsBr/Azure-Templates
      ref: refs/heads/main

variables:
  - template: variables.yml

stages:
  - template: templates/gitflow_calculate_version.yml@templates
    parameters:
      pool: 'Self-hosted'
  - template: templates/library_build.yml@templates
    parameters:
      pool: 'Self-hosted'
      target_frameworks:
        - netstandard2.0
        - net6.0